# this machine readable TOML file defines the common parameters between all tools in this repo.
# It generally contains all the baselined details of the instrument that always apply.
# installed means an optic is present, absent means an optic that has been installed has been removed
# from the physical setup and should not be included in analysis
#OPTICS APPEAR IN ORDER OF INCIDENCE

[Source]
state="installed"
MFG = "HÜBNER Photonics"
Model = "Cobolt 08-NLD (633 nm, 30 mW)"
SN = "30304"
z= ""

[SM Fiber]
state="installed"
MFG = "Schäfter+Kirchhoff"
Model = "PMC-400RGB-3-18E28E-200"
SN =""
z= ""

[Fiber Attenuator]
state="installed"
MFG = "OZoptics"
Model = "DA-100-3A-633-3.5/125-S-50-SP"
SN =""
z= ""

[SM Fiber]
state="installed"
MFG = "ThorLabs"
Model = "P3-S405Y-FC-2"
SN =""
z= ""

[LP]
state="absent"
MFG = "meadowlark optics"
Model = "DP-100-VIS"
URL = "https://www.meadowlark.com/shop/polarizers/precision-linear-polarizer/?17785_attr_pa_wavelength-range-nm%5B0%5D=523&17785_results_per_page=10&17785_filtered=true"
z= ""

[QWP1]
state="absent"
MFG = "BVO"
Model = "AQWP3"
SN="https://boldervision.com/waveplates/aqwp3/"

[LENS1]
state="installed"
MFG = ""
Model = ""
SN =""
FL=""
z=""

[Spatial Filter]
state="installed"
MFG = "UA"
Model = "Custom silicon nitride membrane"
DOI = "10.1117/12.2677630"
Diameter = "5um"
SN= "NA"
z=""
description=""


[OAP1]  # 
state="installed"
purpose="collimator"
MFG = "NuTek"
SN = ""
Diameter = "5um"
FL=""
Coating="Al+MgF2"
z=""

[PUPIL MASK] #
state="installed"
RMS=""
Purpose="pupil mask"
Active_diameter=""
MFG = "MDL JPL (Black Si)"
SN = ""
FL="infinite"

[PUPIL1] #
state="installed"
RX="flat"
RMS=""
Purpose="fine pointing, pupil mask"
Active_diameter=""
MFG = ""
SN = ""
FL="infinite"

[PUPIL1-stage] #
state="installed"
MFG="Newport"
Model=""
SN=""

[OAP2]  #
state="installed"
MFG = ""
SN = ""

[OAP3]  #
state="installed"
MFG = ""
SN = ""

[DM1]
state="installed"
MFG="Boston Micromachines"
Model= "Kilo-C-1.5"
SN="38AW007#029" 
description=""

[Wedged CP]
state="present"
MFG = "BVO"
Model = "30 arc-min prototype"
SN=""

[OAP4]  # 
state="installed"


[FPM]
state="installed"
Model = "Custom VVC (charge 6)"
MFG="BeamCo"
SN="VVW-Q3-BB20Vis-DM45"
description="https://github.com/uasal/cdeep_testbed_operations/issues/97"

[FOLD]
state="installed"
RX="flat"
RMS=""
Active_diameter=""
MFG = ""
SN = ""
FL="infinite"

[OAP5]  # 
state="installed"


[FOLD]
state="installed"
RX="flat"
RMS=""
Active_diameter=""
MFG = ""
SN = ""
FL="infinite"

[LYOT]
state="installed"
Model="Custom Glass"
Coating="100um Al"
MFG="UA"
SN=""
description=""

[OAP6]  # 
state="installed"

[OAP7]  # 
state="installed"

[Wedged CA]
state="present"
MFG = "BVO"
Model = "30 arc-min prototype"
SN=""

[SCI.QWP]
state="absent"
MFG = "BVO"
Model = "AQWP3"
SN="https://boldervision.com/waveplates/aqwp3/"
z= ""

[SCI.LP]
state="absent"
MFG = "meadowlark optics"
Model = "DP-100-VIS"
DOI = "https://www.meadowlark.com/shop/polarizers/precision-linear-polarizer/?17785_attr_pa_wavelength-range-nm%5B0%5D=523&17785_results_per_page=10&17785_filtered=true"
SN =""
z= ""

[SCI.FOLD]
state="installed"

[SCI.L1]
state="installed"


[Sci.Sensor]
state="installed"
MFG = "ZWO"
MODEL = "ASI294MM-Pro"
SN="1812911309020900"
CMOS_QE = ""
description=""

[LOWFS.L1]
state="installed, not used"

[LOWFS.mask]
state="none"

[LOWFS.Sensor]
MFG = "NSV"
MODEL = ""
CMOS_QE = ""
description=""

